StreamBox/Models/Server.cs
using System.ComponentModel.DataAnnotations;

namespace StreamBox.Models
{
    public class Server
    {
        internal object streams;

        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string IP { get; set; }

        [Required]
        [Display(Name = "Max Clients")]
        public int MaxClients { get; set; } 

        [Required]
        [Display(Name = "Root Password")]
        public string RootPassword { get; set; }

        [Display(Name = "HTTP Port")]
        public int HTTPPort { get; set; } = 80;

        [Display(Name = "HTTPS Port")]
        public int HTTPSPort { get; set; } = 443;

        [Display(Name = "RTMP Port")]
        public int RTMPPort { get; set; } = 1935;

        [Display(Name = "SSH Port")]
        public int SSHPort { get; set; } = 22;

        [Display(Name = "Is RTMP?")]
        public bool IsRTMP { get; set; } = false;

        public bool State { get; set; } = false;
    }
}

StreamBox/Controllers/ServerController.cs
using Microsoft.AspNetCore.Mvc;
using Renci.SshNet;
using StreamBox.Models;
using StreamBox.Repositories;
using StreamBox.Helpers;
using System.Threading.Tasks;
using System;
using System.Text;
using System.Threading;

namespace StreamBox.Controllers
{
    public class ServerController : Controller
    {

        private readonly IGenericRepository<Server> Repository;
        public ServerController(IGenericRepository<Server> repository)
        {
            Repository = repository;
        }
        public IActionResult Manage()
        {
            return View(Repository.All());
        }
        public IActionResult Details(int? Id)
        {
            var model = Repository.GetById(Id.Value);
            if (model == null)
            {
                return NotFound();
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new Server());
        }

        [HttpPost]
        public IActionResult Add(Server model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            Repository.Add(model);
            var sbServerIP = ShellHelper.GetServerIPV4();
            var stServerId = model.Id;
            Action runCommand = () => 
            {
                var client = new SshClient(model.IP, "root", model.RootPassword);
                string installScript = System.IO.File.ReadAllText("InstallScripts/Server");
                installScript = string.Format(installScript, sbServerIP, stServerId);
                try 
                {
                    client.Connect();
                    client.RunCommand(installScript);
                }
                finally
                {
                    client.Disconnect();
                    client.Dispose();
                }
            };
            ThreadPool.QueueUserWorkItem(x => runCommand());
            return RedirectToAction(nameof(Details), new { id = model.Id });
        }


        [HttpPost]
        public IActionResult Delete(int Id)
        {
            Repository.Delete(Id);
            return RedirectToAction(nameof(Manage));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            var model = Repository.GetById(id);

            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Server model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);
                return RedirectToAction(nameof(Manage));
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

StreamBox/Views/Server/Add.cshtml
@model Server
@{
    ViewData["Title"] = "Add server";
}

<partial name="~/Views/Partials/Server/_Tab.cshtml"/>

<form id="inputs-items" class="inputs-items" asp-controller="Server" asp-action="Add" method="post">

    <div class="row">

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <input asp-for="@Model.Name" class="form-control"/>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.IP"></label>
                <input asp-for="@Model.IP" class="form-control"/>
                <span asp-validation-for="@Model.IP" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.MaxClients"></label>
                <input asp-for="@Model.MaxClients" class="form-control"/>
                <span asp-validation-for="@Model.MaxClients" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.RootPassword"></label>
                <input asp-for="@Model.RootPassword" class="form-control"/>
                <span asp-validation-for="@Model.RootPassword" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.HTTPPort"></label>
                <input asp-for="@Model.HTTPPort" class="form-control"/>
                <span asp-validation-for="@Model.HTTPPort" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.HTTPSPort"></label>
                <input asp-for="@Model.HTTPSPort" class="form-control"/>
                <span asp-validation-for="@Model.HTTPSPort" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.RTMPPort"></label>
                <input asp-for="@Model.RTMPPort" class="form-control"/>
                <span asp-validation-for="@Model.RTMPPort" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="@Model.SSHPort"></label>
                <input asp-for="@Model.SSHPort" class="form-control"/>
                <span asp-validation-for="@Model.SSHPort" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="@Model.IsRTMP"></label>
                <input asp-for="@Model.IsRTMP"/>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <button class="btn btn-success" type="submit"><i class="fa fa-plus"></i> Add</button>
            </div>
        </div>

    </div>

</form>

StreamBox/Views/Server/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

StreamBox/Views/Server/Details.cshtml
@model Server
@{
    ViewData["Title"] = "Details";
}

<partial name="~/Views/Partials/Server/_Tab.cshtml"/>

<main class="main-container">
    <h1>Details</h1>

    <hr />

    @Model.Name<br />
    @Model.IP

</main>




StreamBox/Views/Server/Manage.cshtml
@model IEnumerable<Server>
@{
    ViewData["Title"] = "Manage servers";
}

<partial name="~/Views/Partials/Server/_Tab.cshtml"/>

<main>
    <div class="main-content-container ">
        <nav class="server-box-nav ">
            <button class="server-button-active">
                <a asp-action="Add" asp-controller="Server">
                    <svg xmlns="http://www.w3.org/2000/svg " width="30 " height="30 " viewBox="0 0 30 30 ">
                        <path id="Icon_material-add-box " data-name="Icon material-add-box "
                              d="M31.167,4.5H7.833A3.332,3.332,0,0,0,4.5,7.833V31.167A3.332,3.332,0,0,0,7.833,34.5H31.167A3.343,3.343,0,0,0,34.5,31.167V7.833A3.343,3.343,0,0,0,31.167,4.5ZM27.833,21.167H21.167v6.667H17.833V21.167H11.167V17.833h6.667V11.167h3.333v6.667h6.667Z "
                              transform="translate(-4.5 -4.5) " fill="#9c9c9c " />
                    </svg>
                </a>
            </button>
        </nav>
        <div id="inputs-container " class="inputs-container">
            <table border="1">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>IP</th>
                        <th>Max Clients</th>
                        <th>State</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var server in Model)
                    {
                        <tr>
                            <td>@server.Name</td>
                            <td>@server.IP</td>
                            <td>@server.MaxClients</td>
                            <td id="@server.Id">
                                @if (server.State)
                                {
                                    <strong style="color:green">Ready</strong>
                                }
                                else
                                {
                                    <strong style="color:red">Proccessing...</strong>
                                }
                            </td>
                            <td>
                                <a asp-controller="Server" asp-action="Edit" asp-route-id="@server.Id">Edit</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</main>

@section Scripts {
    <script src="~/assets/lib/signalr.min.js"></script>
    <script>
        window.addEventListener('load', () => {
            let connection = new signalR.HubConnectionBuilder().withUrl("/server-update-hub").build();
            connection.start();
            connection.on("Update", serverId => {
                document.getElementById(serverId).innerHTML = '<strong style="color:green">Ready</strong>';
            });
        });
    </script>
}

StreamBox/Views/Server/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>